name: CI/CD Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      NODE_ENV: production
      API_URL: "https://meuapp.com/api"

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Usar segredo 
        env:
          API_SECURITY_TOKEN_SECRET: ${{ secrets.API_SECURITY_TOKEN_SECRET }}
        run: echo "Chave API carregada"

      - name: Mostrar URL configurad
        run: echo "Usando API em $API_URL"

      - name: Compilar e rodar testes com perfil de testes
        working-directory: backend
        run: mvn clean verify -Dspring.profiles.active=test
